// js/ui/themes/themePresets.js - 内置主题预设
export const THEME_PRESETS = {
  light: {
    id: 'light',
    name: '亮色',
    variables: {
      '--color-bg-primary': '#ffffff',
      '--color-bg-secondary': '#f8f9fd',
      '--color-bg-sidebar': '#f0f2f8',
      '--color-bg-input': '#ffffff',
      '--color-text-primary': '#1a1a2e',
      '--color-text-secondary': '#4a4a6a',
      '--color-text-muted': '#8a8aaa',
      '--color-border': '#e8ecf4',
      '--color-border-light': '#f0f2f8',
      '--color-primary': '#6c5ce7',
      '--color-primary-light': '#a29bfe',
      '--color-primary-dark': '#4a3db8',
      '--color-primary-gradient': 'linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%)',
      '--color-primary-gradient-hover': 'linear-gradient(135deg, #5a4bd1 0%, #8c7ef0 100%)',
      '--color-secondary': '#00b894',
      '--color-secondary-light': '#55efc4',
      '--color-secondary-dark': '#00a381',
      '--color-danger': '#e17055',
      '--color-danger-light': '#fab1a0',
      '--color-danger-dark': '#d63031',
      '--color-warning': '#fdcb6e',
      '--color-warning-light': '#ffeaa7',
      '--shadow-xs': '0 1px 2px rgba(0, 0, 0, 0.04)',
      '--shadow-sm': '0 2px 8px rgba(0, 0, 0, 0.06)',
      '--shadow-md': '0 4px 16px rgba(108, 92, 231, 0.12)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.12)',
      '--shadow-xl': '0 12px 48px rgba(0, 0, 0, 0.18)',
      '--radius-xs': '4px',
      '--radius-sm': '6px',
      '--radius-md': '8px',
      '--radius-lg': '12px',
      '--radius-xl': '16px',
      '--radius-2xl': '24px',
      '--radius-full': '9999px',
    }
  },
  dark: {
    id: 'dark',
    name: '暗色',
    variables: {
      '--color-bg-primary': '#1a1a2e',
      '--color-bg-secondary': '#16213e',
      '--color-bg-sidebar': '#0f0f1a',
      '--color-bg-input': '#25254a',
      '--color-text-primary': '#e8e8f0',
      '--color-text-secondary': '#a0a0c0',
      '--color-text-muted': '#6a6a8a',
      '--color-border': '#2a2a4a',
      '--color-border-light': '#1f1f3a',
      '--color-primary': '#a29bfe',
      '--color-primary-light': '#b8b3ff',
      '--color-primary-dark': '#6c5ce7',
      '--color-primary-gradient': 'linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%)',
      '--color-primary-gradient-hover': 'linear-gradient(135deg, #5a4bd1 0%, #8c7ef0 100%)',
      '--color-secondary': '#55efc4',
      '--color-secondary-light': '#81ecec',
      '--color-secondary-dark': '#00b894',
      '--color-danger': '#e17055',
      '--color-danger-light': '#fab1a0',
      '--color-danger-dark': '#d63031',
      '--color-warning': '#fdcb6e',
      '--color-warning-light': '#ffeaa7',
      '--shadow-xs': '0 1px 2px rgba(0, 0, 0, 0.5)',
      '--shadow-sm': '0 2px 8px rgba(0, 0, 0, 0.6)',
      '--shadow-md': '0 4px 16px rgba(108, 92, 231, 0.3)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.7)',
      '--shadow-xl': '0 12px 48px rgba(0, 0, 0, 0.8)',
      '--radius-xs': '4px',
      '--radius-sm': '6px',
      '--radius-md': '8px',
      '--radius-lg': '12px',
      '--radius-xl': '16px',
      '--radius-2xl': '24px',
      '--radius-full': '9999px',
    }
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: '赛博朋克',
    variables: {
      '--color-bg-primary': '#0a0a1a',
      '--color-bg-secondary': '#1a0a2e',
      '--color-bg-sidebar': '#0a0a1a',
      '--color-bg-input': '#1a0a2e',
      '--color-text-primary': '#00ffcc',
      '--color-text-secondary': '#ff00ff',
      '--color-text-muted': '#8844aa',
      '--color-border': '#ff00ff44',
      '--color-border-light': '#00ffcc22',
      '--color-primary': '#ff00ff',
      '--color-primary-light': '#ff88ff',
      '--color-primary-dark': '#cc00cc',
      '--color-primary-gradient': 'linear-gradient(135deg, #ff00ff 0%, #00ffcc 100%)',
      '--color-primary-gradient-hover': 'linear-gradient(135deg, #cc00cc 0%, #00ccaa 100%)',
      '--color-secondary': '#00ffcc',
      '--color-secondary-light': '#88ffdd',
      '--color-secondary-dark': '#00ccaa',
      '--color-danger': '#ff4444',
      '--color-danger-light': '#ff8888',
      '--color-danger-dark': '#cc0000',
      '--color-warning': '#ffaa00',
      '--color-warning-light': '#ffcc44',
      '--shadow-xs': '0 1px 2px rgba(0, 255, 204, 0.1)',
      '--shadow-sm': '0 2px 8px rgba(255, 0, 255, 0.2)',
      '--shadow-md': '0 4px 16px rgba(255, 0, 255, 0.3)',
      '--shadow-lg': '0 8px 32px rgba(255, 0, 255, 0.4)',
      '--shadow-xl': '0 12px 48px rgba(255, 0, 255, 0.5)',
      '--radius-xs': '0px',
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-lg': '8px',
      '--radius-xl': '12px',
      '--radius-2xl': '16px',
      '--radius-full': '0px',
    }
  }
};

export function getThemeVariables(id) {
  return THEME_PRESETS[id]?.variables || null;
}